base_url = "https://example.com"
title = "Keru"
description = "A site for the Keru GUI library."
compile_sass = true
build_search_index = false

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
