base_url = "https://kekelp.github.io/keru"
title = "Keru"
description = "A website for the Keru GUI library."
compile_sass = true
build_search_index = false

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
