base_url = "http://127.0.0.1:1111"
title = "Keru"
compile_sass = false
build_search_index = false

[extra]
videos = [
    "aesthetics_scifi.mp4",
    "aesthetics_water.mp4",
    "airbnb_month_slider.mp4",
    "animated_shapes.mp4",
    "animations.mp4",
    "custom_rendering.mp4",
    "grid.mp4",
    "interactive_plot.mp4",
]
